spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 21392441664-tntvoa0jjc8bt538pnes9dvmfqddpuik.apps.googleusercontent.com
            clientSecret: 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


server:
  port: 8080